# Site settings
title: Plumatic Blog
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "https://plumatic.github.io/" # the subpath of your site, e.g. /blog/
url: "https://github.com/plumatic/"
#twitter_username: jekyllrb
#github_username:  jekyll
#
permalink: /:title

# Build settings
markdown: kramdown
